#!/bin/env zsh

eval $(/opt/homebrew/bin/brew shellenv)
alias ls=exa
alias ll="ls --group-directories-first -la"
alias getenv="launchctl getenv"
alias k=kubectl
alias p=python3
alias cf=codefresh
alias vim=nvim
alias e="fzf | xargs nvim"
    

MY_PATH+="/Users/dorontsur/bin:"
MY_PATH+="/Users/dorontsur/.deno/bin:"
MY_PATH+="/Users/dorontsur/.local/bin:"
MY_PATH+="/Users/dorontsur/local/bin:"
MY_PATH+="/Users/doron.tsur/Library/Python/3.8/bin:"
MY_PATH+="/Users/dorontsurcargo/bin/:"
MY_PATH+="/Users/dorontsur/go/bin/:"
MY_PATH+=$PATH
export PATH=$MY_PATH

function lsp {
  lsof -PiTCP -sTCP:LISTEN
}

HOST_IP=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)

GOPRIVATE="github.com/honeybook/*"

export EDITOR=nvim

export CARGO_NET_GIT_FETCH_WITH_CLI=true
export DOT_SOURCE="~/code/dotty"
alias ghome="ssh home@192.168.0.157"


eval "$(starship init zsh)"
eval "$(zellij setup --generate-auto-start zsh)"
eval "$(fnm env --use-on-cd)"

_codefresh_completions()
{
    type_list=($(codefresh --impl-zsh-file-dir --get-yargs-completions "${words[@]}"))

    if [[ ${type_list[1]} == '__files_completion__' ]]; then
        compadd -- "${type_list[@]:1}"
    else
        compadd -- "${type_list[@]}"
    fi

    return 0
}
compdef _codefresh_completions codefresh
###-end-codefresh-completions-###
source /Users/dorontsur/code/dotty/no-commit
