#!/bin/zsh

eval "$(fnm env --use-on-cd)"

alias ls=exa
alias ll="ls --group-directories-first -la"
alias getenv="launchctl getenv"
alias vim nvim
alias k kubectl
alias p python3
alias vim lvim 
alias ghome="ssh home@192.168.0.157"

export PATH=~/bin:$PATH 
export PATH=~/.deno/bin:$PATH 
export PATH=~/.cargo/bin:$PATH 
export PATH=~/.cargo/bin:$PATH 
export PATH=~/go/bin:$PATH 

function lsp () {
  lsof -PiTCP -sTCP:LISTEN
}

export HOST_IP=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)

export GOPRIVATE="github.com/honeybook/*"

bindkey -v 
if [[ -z "$ZELLIJ" ]]; then
    if [[ "$ZELLIJ_AUTO_ATTACH" == "true" ]]; then
        zellij attach -c
    else
        zellij
    fi

    if [[ "$ZELLIJ_AUTO_EXIT" == "true" ]]; then
        exit
    fi
fi

