#!/bin/env zsh

eval $(/opt/homebrew/bin/brew shellenv)
alias ls=exa
alias ll="ls --group-directories-first -la"
alias getenv="launchctl getenv"
alias vim=nvim
alias k=kubectl
alias p=python3

PATH="~/bin:$PATH"
PATH="~/.deno/bin:$PATH"
PATH="/Users/dorontsur/.local/bin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="/Users/doron.tsur/Library/Python/3.8/bin:$PATH"
PATH="~/.cargo/bin/:$PATH"
PATH="~/go/bin/:$PATH"
export PATH

function lsp {
  lsof -PiTCP -sTCP:LISTEN
}

HOST_IP=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)

GOPRIVATE="github.com/honeybook/*"

export EDITOR=nvim

# define golang
export GOBIN="~/go/bin"


export CARGO_NET_GIT_FETCH_WITH_CLI=true
export DOT_SOURCE="~/code/dotty"
alias ghome="ssh home@192.168.0.157"


eval "$(starship init zsh)"
eval "$(zellij setup --generate-auto-start zsh)"
