#!/usr/bin/env bash

function create_link() {
    if [ $# -eq 3 ]; then
        echo "making folder" $3
        mkdir -p $3
    fi
    if [ -e "$2" ]; then
            echo "$2 exist"
        else
            ln -s "$(pwd)/$1" "$2"
    fi
}

create_link alacritty.yml ~/.config/alacritty/alacritty.yml ~/.config/alacritty
create_link config.fish ~/.config/fish/config.fish ~/.config/fish
create_link gitconfig ~/.gitconfig  
create_link ./vim-config/plugins.vim ~/.config/nvim/vim-config/plugins.vim
create_link ./vim-config/options.vim ~/.config/nvim/vim-config/options.vim
create_link ./vim/init.lua ~/.config/nvim/init.lua

if [ "$(uname)" == "Linux" ]; then
    echo "Os is Linux"
else
    isFish=$(which fish)
    if [[ -z "$isFish" ]]; then
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
    else
        echo fish is already installed
    fi
    brew install eth-p/software/bat-extras.
    brew install kubernetes-cli
    brew install exa
    brew install bat
    brew install jq
    brew install ack
    brew install htop
    brew install --cask alacritty
    brew install hugo
    brew install diff-so-fancy
    brew install pyenv
fi

